name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch: 

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install libbsc (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install libbsc
      if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          git clone https://github.com/IlyaGrebnov/libbsc.git
          cd libbsc
          cmake .
          make
          sudo make install
          cd ..
          rm -rf libbsc
    - name: Run tests
      run: bundle exec rake
